version: '3' 

services: 
  infotv-db: 
    image: mariadb 
    environment: 
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
    volumes: 
      - ./infotv-db:/var/lib/mysql 
    ports: 
      - 3306:3306

  infotv-redis:
    image: redis 
    volumes: 
      - ./infotv-redis:/data 
    ports: 
      - 6379:6379 

  infotv-backend:
    build: ./backend  
    environment: 
      DBCONN: 
      REDISCONN: 
    ports: 
      - 8080:80
    depends_on: 
      - infotv-db
      - infotv-redis

  infotv-slackbot:
    build: ./slackbot 
    environment: 
      SLACK_API_TOKEN: 
      API_IP:  
      API_PORT: 
    depends_on:
      - infotv-backend 

